"""Add custom_token to supermarkets

Revision ID: 54edbd84ad87
Revises: be1fb9949d94
Create Date: 2025-10-30 14:27:06.971078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54edbd84ad87'
down_revision: Union[str, Sequence[str], None] = 'be1fb9949d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
