"""Add missing columns to supermarkets

Revision ID: be1fb9949d94
Revises: ef17c3a03162
Create Date: 2025-10-27 00:45:27.783392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'be1fb9949d94'
down_revision: Union[str, Sequence[str], None] = 'ef17c3a03162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supermarkets_email'), table_name='supermarkets')
    op.drop_index(op.f('ix_supermarkets_id'), table_name='supermarkets')
    op.drop_table('supermarkets')
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_supermarket_history_id'), table_name='supermarket_history')
    op.drop_index(op.f('ix_supermarket_history_supermarket_id'), table_name='supermarket_history')
    op.drop_table('supermarket_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermarket_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supermarket_id', sa.INTEGER(), nullable=False),
    sa.Column('campo_alterado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('valor_anterior', sa.TEXT(), nullable=True),
    sa.Column('valor_novo', sa.TEXT(), nullable=True),
    sa.Column('usuario_alteracao', sa.VARCHAR(), nullable=False),
    sa.Column('data_alteracao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supermarket_history_supermarket_id'), 'supermarket_history', ['supermarket_id'], unique=False)
    op.create_index(op.f('ix_supermarket_history_id'), 'supermarket_history', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('nome_cliente', sa.VARCHAR(), nullable=False),
    sa.Column('valor_total', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('data_pedido', sa.DATETIME(), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['supermarkets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=2), nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['supermarkets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=1)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['supermarkets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('itens_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('nome_produto', sa.VARCHAR(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.create_table('supermarkets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=9), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=2), nullable=False),
    sa.Column('horario_funcionamento', sqlite.JSON(), nullable=True),
    sa.Column('metodos_pagamento', sqlite.JSON(), nullable=True),
    sa.Column('categorias_produtos', sqlite.JSON(), nullable=True),
    sa.Column('capacidade_estocagem', sa.INTEGER(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), nullable=True),
    sa.Column('plano', sa.VARCHAR(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supermarkets_id'), 'supermarkets', ['id'], unique=False)
    op.create_index(op.f('ix_supermarkets_email'), 'supermarkets', ['email'], unique=1)
    # ### end Alembic commands ###
